config/routes.rb
SampleApp::Application.routes.draw do
 
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

 

 root :to => "pages/home"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	  @titre = "Accueil"
  end

  def contact
	  @titre = "Contact"
  end

  def about
	  @titre = "A Propos"
  end

  def help
	@titre = "Aide"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#retourne un titre basé sur la page
def titre
	base_titre = "Simple App du Tutoriel Ruby on rails"
	if @titre.nil?
		base_titre
	else
		"#{base_titre} | #{@titre}"
	end
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
      <ul>
           <li><%= link_to "À Propos", about_path %></li>
	         <li><%= link_to "Contact", contact_path %></li>
		    <li><a href="http://news.railstutorial.org/">News</a></li>
		      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
          </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("logo.png", :alt => "Application exemple", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
        <ul>
	      <li><%= link_to "Accueil", root_path %></li>
	            <li><%= link_to "Aide", help_path %></li>
		          <li><%= link_to "Connexion", '#' %></li>
	  </ul>
       </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	 <head>
	      <title><%= titre %></title>
	          <%= csrf_meta_tag %>
		  <%= render 'layouts/stylesheets' %>
	 </head>
	  <body>
	      <div class="container">
	            <%= render 'layouts/header' %>
		       <section class="round">
		          <%= yield %>
		        </section>
		    <%= render 'layouts/footer' %>
		</div>
	 </body>
 </html>

app/views/pages/about.html.erb
<h1> A Propos de nous</h1>
<p>
<a href "http://rubyonrails.org/">Ruby on Rails Tutorial</a>
est un projet de livre et de screecats pour apprendre le developpement web avec <a href="http://rubyonrails.org/">Ruby on Rails</a>
. C'est l'application exemple de ce tutoriel
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
Contact du Tutoriel Ruby on Rails à propos de l'application Exemple à la 
<a href="http://rubyonrails.org/feedback">page de feedback</a>
</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
    <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
      Pour obtenir de l'aide sur cette application exemple, consultez le
      <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
C'est la page d'accueil de l'application Exemple du 
<a href="http://rubyonrails.org/">Tutoriel Ruby on Rails</a>
</p
<%= link_to "S'inscrire&nbsp;!", '#', :class => "signup_button round" %>